orbs: # declare what orbs we are going to use
  node: circleci/node@5.0.0 # the node orb provides common node-related configuration
version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: 12.22.10
      - run:
          name: installing the project dependencies
          command: npm run install
      - run:
          name: building the project
          command: export CI=false && npm run build
      - run:
          name: running the project tests
          command: npm run test
          
workflows:
  workflow:                    
    jobs:
      - build:  
          filters:
            branches:
               only:                
                  - main
